server:
  port: 8084

spring:
  application:
    name: inui-kafka-service
  data:
    mongodb:
      uri: mongodb://Guru99:password@localhost:27017/inui
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: inui-library-service
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092
    topics:
      inui-service-topic: inui-profile-service
      inui-gw-topic: inui-gw-topic
inui:
  userprofile:
    enableKafka: true
    gateaway-topic: inui-gw-topic
    notification-topic: inui-notification-service
    chat-topic: inui-chat-service
    input-topic: inui-profile-service
    debug-topic: inui-profile-service-debug
    file-storage-topic: inui-file-service
logging:
  level:
    org.apache.kafka.clients: WARN